version: '3'
services:
    mongo:
        image: "mongo"
        restart: always
        networks: 
            - backend
        expose: 
            - '27017'
        ports:
            - "27017:27017"

    mysql:
        image: mysql
        # command: --default-authentication-plugin=mysql_native_password
        restart: always
        container_name: mysql
        networks: 
            - backend
        expose: 
            - 3306
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: admin
        restart: always
        links:
            - mysql:mysql
        ports:
            - 9191:80
        networks: 
            - backend
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: root
            PMA_HOST: mysql

    usermanagement:
        image: usermanagement
        build: ./user
        restart: always
        container_name: usermanagement
        networks: 
            - backend
        expose: 
            - '5001'
        command: "node user.js"
        ports:
            - "5001:5001"
        depends_on:
            - "mongo"
            - "mysql"
        links:
            - mysql:mysql
            - mongo:mongo
                
    filesever:
        image: fileserver
        build: ./fileServer
        restart: always
        container_name: fileserver
        networks: 
            - backend
        expose: 
            - '5004'
        command: "node fileServer.js"
        ports:
            - "5004:5004"
        depends_on:
            - "mongo"
            - "mysql"
        links:
            - mysql:mysql
            - mongo:mongo
                
    setups:
        image: setups
        build: ./server
        container_name: setups
        networks: 
            - backend
        expose: 
            - 5006
        command: "npm start"
        ports:
            - "5006:5006"
        depends_on:
            - "mysql"
        links:
            - mysql:mysql
            
    match:
        image: match
        build: ./match
        container_name: match
        networks: 
            - backend
        expose: 
            - 5005
        command: "npm start"
        ports:
            - "5005:5005"
        depends_on:
            - "mysql"
        links:
            - mysql:mysql
    load:
        image: load
        build: ./load
        restart: always
        container_name: load
        networks: 
            - backend
        #     - backenddb
        expose: 
            - '3020'
        command: "npm start"
        ports:
            - "3020:3020"

    # client:
    #     image: client
    #     build: ./client
    #     restart: always
    #     container_name: client
    #     expose: 
    #         - '3001'
    #     command: "npm start"
    #     ports:
            # - "3001:3000"
networks:
    backend:
        driver: bridge


    