version: '2'
services:
    mongo:
        image: "mongo"
        networks: 
            - backenddb
        expose: 
            - '27017'
        ports:
            - "27017:27017"

    usermanagement:
        image: usermanagement
        build: ./user
        container_name: usermanagement
        # links: 
            # - "nginx"
        networks: 
            - backend
            - backenddb
        expose: 
            - '5001'
        command: "node user.js"
        ports:
            - "5001:5001"
        depends_on:
            - "mongo"
                
    filesever:
        image: fileserver
        build: ./fileServer
        container_name: fileserver
        networks: 
            - backend
            - backenddb
        expose: 
            - '5004'
        command: "node fileServer.js"
        ports:
            - "5004:5004"
        depends_on:
            - "mongo"
                
    nginx:
        build: ./nginx
        container_name: nginx   
        restart: always
        links: 
            - "usermanagement"
            # - "fileserver"
        networks:
            - backend
        ports: 
            - 80:80
        # volumes: 
            # - ./nginx/defualt.conf:/etc/nginx/conf.d/defualt.conf
                # client_frontend:
        #     image: client
        #     build: ./client
        #     command: "npm start"
        #     ports:
        #         - "80:3000"
networks:
    backend:
        driver: bridge
    backenddb:
        driver: bridge


    